
@ECHO OFF

REM git init

SET TARGET_PATH=D:\Repos\Nu2\webgl\src\
SET SOURCE_PATH=D:\Repos\Nu2\NetApi\

SET SOLUTION_FILE=WebGl

SET SOURCE_PROJECTS=
SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.Core.Contracts
SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.Core.Business 
SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.Core.Controllers 
SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.Core.Persistence
SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.Api

SET SOURCE_PROJECTS=%SOURCE_PROJECTS% Nucleus.AspNetCore.Mvc

SET SOURCE_FOLDERS=
SET SOURCE_FOLDERS=%SOURCE_FOLDERS% .config

SET SOURCE_FILES=
SET SOURCE_FILES=%SOURCE_FILES% Directory.Build.targets
SET SOURCE_FILES=%SOURCE_FILES% Directory.Build.props

SET SOURCE_FILES2=
SET SOURCE_FILES2=%SOURCE_FILES2% GitVersion.yml
SET SOURCE_FILES2=%SOURCE_FILES2% Nuget.config
SET SOURCE_FILES2=%SOURCE_FILES2% .gitignore
 
PUSHD %TARGET_PATH%
CALL :NEW_SOLUTION %TARGET_PATH%
CALL :COPY_PROJECT_TO %SOURCE_PROJECTS%
CALL :COPY_PROJECT_TO %SOURCE_FILES%
CALL :COPY_FILE_TO %SOURCE_FILES%
CALL :COPY_FILE_TO2 %SOURCE_FILES2%
CALL :ADD_PROJECT_TO %SOURCE_PROJECTS%
dotnet tool restore
POPD

GOTO :EOF

:NEW_SOLUTION
dotnet new solution --name %SOLUTION_FILE%
EXIT /B

:COPY_PROJECT_TO
SET TEMP_ITEM=%1
IF "%TEMP_ITEM%"=="" EXIT /B
ECHO Copy Project: %TEMP_ITEM%
ROBOCOPY "%SOURCE_PATH%%TEMP_ITEM%" "%TARGET_PATH%%TEMP_ITEM%" /E /MIR /XD obj /XD bin /XO
SHIFT
GOTO :COPY_PROJECT_TO

:COPY_FILE_TO
SET TEMP_ITEM=%1
IF "%TEMP_ITEM%"=="" EXIT /B
ECHO Copy File: %TEMP_ITEM%
COPY "%SOURCE_PATH%%TEMP_ITEM%" "%TARGET_PATH%%TEMP_ITEM%"
SHIFT
GOTO :COPY_FILE_TO

:COPY_FILE_TO2
SET TEMP_ITEM=%1
IF "%TEMP_ITEM%"=="" EXIT /B
ECHO Copy File: %TEMP_ITEM%
COPY "%SOURCE_PATH%%TEMP_ITEM%" "%TARGET_PATH%%TEMP_ITEM%\.."
SHIFT
GOTO :COPY_FILE_TO2

:ADD_PROJECT_TO
SET TEMP_ITEM=%1
IF "%TEMP_ITEM%"=="" EXIT /B
ECHO Add Project: %TEMP_ITEM%
dotnet sln %SOLUTION_FILE%.sln add %TEMP_ITEM%\%TEMP_ITEM%.csproj
SHIFT
GOTO :ADD_PROJECT_TO
