
@ECHO OFF

SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION

SET APPLICATION_NAME=nucleus
SET APPLICATION_QUEUES=%APPLICATION_NAME%-events %APPLICATION_NAME%-communications test-queue another
SET APPLICATION_QUEUES=%APPLICATION_QUEUES% email-send email-receive
SET APPLICATION_CONTAINERS=%APPLICATION_NAME%-blobs
SET APPLICATION_TABLES=%APPLICATION_NAME%-data

SET AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;QueueEndpoint=http://localhost:10001/devstoreaccount1;TableEndpoint=http://localhost:10002/devstoreaccount1

CALL :BUILD_QUEUES %APPLICATION_QUEUES%
CALL :BUILD_CONTAINERS %APPLICATION_CONTAINERS%
CALL :BUILD_TABLES %APPLICATION_TABLES%

GOTO DONE

:BUILD_QUEUES
SET CURRENT_ITEM=%1
SHIFT
IF "%CURRENT_ITEM%"=="" GOTO :EOF
ECHO Create "%CURRENT_ITEM%" Queue
CALL az storage queue create --name "%CURRENT_ITEM%"
GOTO BUILD_QUEUES

:BUILD_CONTAINERS
SET CURRENT_ITEM=%1
SHIFT
IF "%CURRENT_ITEM%"=="" GOTO :EOF
ECHO Create "%CURRENT_ITEM%" Container
CALL az storage container create --name "%CURRENT_ITEM%"
GOTO BUILD_CONTAINERS

:BUILD_TABLES
SET CURRENT_ITEM=%1
SHIFT
IF "%CURRENT_ITEM%"=="" GOTO :EOF
ECHO Create "%CURRENT_ITEM%" Table
CALL az storage container create --name "%CURRENT_ITEM%"
GOTO BUILD_TABLES

:DONE
 ECHO fin!
ENDLOCAL

 :EOF
 EXIT /B